No error when cycles doesn't match
phate/hls-test-suite pull request #18
Opened 2024-12-20 10:51 UTC by sjalander

2024-12-20 11:50 UTC, haved approved these changes, later dismissed
Good for now, I wish GitHub would implement https://github.com/actions/runner/issues/2347, but it is 2.5 years old by now

2024-12-20 11:53 UTC, phate requested changes
Could we get a FIXME comment on this as well so we know why it returns 0 instead of 1. This will otherwise be forgotten.

2024-12-24 08:49 UTC, phate commented
@sjalander Ping

2024-12-24 11:16 UTC, phate approved these changes

2024-12-24 11:16 UTC, merged